export const CONFIG_API_EXTRA_NAMES = ['typescript', 'rust', 'git', 'ai', 'formatting', 'debug'] as const
export const CONFIG_API_PANEL_NAMES = ['shell', 'ai', 'git', 'diagnostics', 'commandPalette'] as const
export const CONFIG_API_DIRECTIVE_TYPES = [
  'shell.run',
  'panel.open',
  'openFile',
  'editor.insert',
  'editor.move',
  'command.run',
  'ui.notify',
] as const
export const CONFIG_API_HOOK_NAMES = ['onSave', 'onOpen', 'onChange'] as const

export function configApiTemplate(): string {
  return [
    `// Local qe config typing helper. Generated next to config.ts so this setup is portable.`,
    `export type QeExtra = ${CONFIG_API_EXTRA_NAMES.map(name => `'${name}'`).join(' | ')}`,
    `export type ConfigNotifyLevel = 'info' | 'warn' | 'error'`,
    `export type ConfigPanelName = ${CONFIG_API_PANEL_NAMES.map(name => `'${name}'`).join(' | ')}`,
    `export type ConfigPickItem = string | { label: string; value?: string; description?: string }`,
    `export type ConfigDirective =`,
    `  | { type: 'shell.run'; command: string }`,
    `  | { type: 'panel.open'; panel: ConfigPanelName; options?: Record<string, unknown> }`,
    `  | { type: 'openFile'; path: string; row?: number; col?: number }`,
    `  | { type: 'editor.insert'; text: string }`,
    `  | { type: 'editor.move'; direction: string }`,
    `  | { type: 'command.run'; command: string; args?: Record<string, unknown> }`,
    `  | { type: 'ui.notify'; message: string; level?: ConfigNotifyLevel }`,
    `export type ConfigActionResult = void | ConfigDirective | ConfigDirective[] | Promise<void | ConfigDirective | ConfigDirective[]>`,
    `export type EditorContext = {`,
    `  readonly filename: string | null`,
    `  readonly lines: string[]`,
    `  readonly cursor: { row: number; col: number }`,
    `  save: () => void`,
    `  quit: () => void`,
    `  insert: (text: string) => void`,
    `  move: (dir: string) => void`,
    `  openFile: (path: string, jump?: { row: number; col: number }) => void`,
    `  shell: { run: (cmd: string) => void; lines: () => string[] }`,
    `  buffers: { list: () => unknown[]; current: () => unknown | null; switch: (id: string) => void; kill: (id?: string) => void; next: () => void; previous: () => void }`,
    `  commands: { run: (id: string, args?: Record<string, unknown>) => Promise<void> }`,
    `  ui: { pick: (title: string, items: ConfigPickItem[]) => Promise<string | null>; input: (title: string, initial?: string) => Promise<string | null>; confirm: (title: string, body?: string) => Promise<boolean>; notify: (message: string, level?: ConfigNotifyLevel) => void; panel: (name: ConfigPanelName, options?: Record<string, unknown>) => void }`,
    `  git: { status: () => void; stageCurrentFile: () => void; stageHunk: () => void; previewHunk: () => void }`,
    `  lsp: { hover: () => void; definition: () => void; format: () => void }`,
    `  diagnostics: { list: () => void; next: () => void; line: () => void }`,
    `}`,
    `export type ConfigAction = string | { command: string; args?: Record<string, unknown>; label?: string } | ConfigDirective | ConfigDirective[] | ((ctx: EditorContext) => ConfigActionResult)`,
    `export type QeConfig = {`,
    `  preset?: 'web' | 'rust' | 'minimal'`,
    `  extras?: QeExtra[]`,
    `  theme?: Partial<Record<'bg' | 'fg' | 'grey' | 'red' | 'orange' | 'green' | 'yellow' | 'blue' | 'magenta' | 'cyan' | 'violet', string>>`,
    `  leader?: { [key: string]: ConfigAction | QeConfig['leader'] }`,
    `  hooks?: { ${CONFIG_API_HOOK_NAMES.map(name => `${name}?: ConfigAction`).join('; ')} }`,
    `  commands?: Record<string, ConfigAction>`,
    `}`,
    `export function defineConfig<const T extends QeConfig>(config: T): T { return config }`,
  ].join('\n')
}

export function starterConfigTemplate(): string {
  return [
    `// ~/.config/qe/config.ts - qe programmable editor config`,
    `// This file is trusted local code. It can use command IDs, directives, or functions.`,
    `import { defineConfig } from './config-api.ts'`,
    ``,
    `export default defineConfig({`,
    `  preset: 'web',`,
    `  extras: ['typescript', 'git', 'ai', 'formatting'],`,
    ``,
    `  commands: {`,
    `    'tasks.pickAndRun': async (ctx) => {`,
    `      const task = await ctx.ui.pick('Run task', [`,
    `        'npm run typecheck',`,
    `        'npm --prefix app run test',`,
    `        'cargo test --manifest-path native/editor-core/Cargo.toml',`,
    `      ])`,
    `      if (task) return [`,
    `        { type: 'shell.run', command: task },`,
    `        { type: 'panel.open', panel: 'shell' },`,
    `      ]`,
    `    },`,
    `  },`,
    ``,
    `  leader: {`,
    `    p: { t: 'tasks.pickAndRun' },`,
    `    x: { t: [`,
    `      { type: 'shell.run', command: 'npm test' },`,
    `      { type: 'panel.open', panel: 'shell' },`,
    `    ] },`,
    `    z: { r: (ctx) => ctx.shell.run('cargo test') },`,
    `  },`,
    ``,
    `  hooks: {`,
    `    // Hooks support commands/directives. Interactive UI prompts are only available from leader commands.`,
    `    onSave: async (ctx) => {`,
    `      if (ctx.filename?.endsWith('.ts')) await ctx.commands.run('code.format')`,
    `    },`,
    `    // onChange fires only when content revision changes, after the initial snapshot, debounced by 250ms.`,
    `    // onChange: { type: 'ui.notify', message: 'buffer changed' },`,
    `  },`,
    `})`,
  ].join('\n')
}
