export const CONFIG_API_EXTRA_NAMES = ['typescript', 'rust', 'git', 'ai', 'formatting', 'debug'] as const
export const CONFIG_API_PANEL_NAMES = ['shell', 'ai', 'git', 'diagnostics', 'commandPalette'] as const
export const CONFIG_API_DIRECTIVE_TYPES = [
  'shell.run',
  'panel.open',
  'openFile',
  'editor.insert',
  'editor.move',
  'command.run',
  'ui.notify',
  'ui.splash',
] as const
export const CONFIG_API_HOOK_NAMES = ['onSave', 'onOpen', 'onChange', 'onBufEnter', 'onShellDone'] as const

export function configApiTemplate(): string {
  return [
    `// Local qe config typing helper. Generated next to config.ts so this setup is portable.`,
    `export type QeExtra = ${CONFIG_API_EXTRA_NAMES.map(name => `'${name}'`).join(' | ')}`,
    `export type ConfigNotifyLevel = 'info' | 'warn' | 'error'`,
    `export type ConfigPanelName = ${CONFIG_API_PANEL_NAMES.map(name => `'${name}'`).join(' | ')}`,
    `export type ConfigPickItem = string | { label: string; value?: string; description?: string }`,
    `export type ConfigDirective =`,
    `  | { type: 'shell.run'; command: string }`,
    `  | { type: 'panel.open'; panel: ConfigPanelName; options?: Record<string, unknown> }`,
    `  | { type: 'openFile'; path: string; row?: number; col?: number }`,
    `  | { type: 'editor.insert'; text: string }`,
    `  | { type: 'editor.move'; direction: string }`,
    `  | { type: 'command.run'; command: string; args?: Record<string, unknown> }`,
    `  | { type: 'ui.notify'; message: string; level?: ConfigNotifyLevel }`,
    `  | { type: 'ui.splash'; title: string; message?: string; hint?: string }`,
    `export type ConfigActionResult = void | ConfigDirective | ConfigDirective[] | Promise<void | ConfigDirective | ConfigDirective[]>`,
    `export type ShellRun = {`,
    `  id: string`,
    `  command: string`,
    `  cwd: string`,
    `  startedAt: string`,
    `  endedAt?: string`,
    `  exitCode?: number`,
    `  stdout: string`,
    `  stderr: string`,
    `  locations: { file: string; row: number; col: number; message: string }[]`,
    `}`,
    `export type EditorContext = {`,
    `  readonly filename: string | null`,
    `  readonly lines: string[]`,
    `  readonly cursor: { row: number; col: number }`,
    `  readonly lastShellRun: ShellRun | null`,
    `  save: () => void`,
    `  quit: () => void`,
    `  insert: (text: string) => void`,
    `  move: (dir: string) => void`,
    `  openFile: (path: string, jump?: { row: number; col: number }) => void`,
    `  shell: { run: (cmd: string) => void; lines: () => string[] }`,
    `  buffers: { list: () => unknown[]; current: () => unknown | null; switch: (id: string) => void; kill: (id?: string) => void; next: () => void; previous: () => void }`,
    `  commands: { run: (id: string, args?: Record<string, unknown>) => Promise<void> }`,
    `  ui: { pick: (title: string, items: ConfigPickItem[]) => Promise<string | null>; input: (title: string, initial?: string) => Promise<string | null>; confirm: (title: string, body?: string) => Promise<boolean>; notify: (message: string, level?: ConfigNotifyLevel) => void; panel: (name: ConfigPanelName, options?: Record<string, unknown>) => void; splash: (options: { title: string; message?: string; hint?: string }) => void }`,
    `  git: { status: () => void; stageCurrentFile: () => void; stageHunk: () => void; previewHunk: () => void }`,
    `  lsp: { hover: () => void; definition: () => void; format: () => void }`,
    `  diagnostics: { list: () => void; next: () => void; line: () => void }`,
    `}`,
    `export type ConfigAction = string | { command: string; args?: Record<string, unknown>; label?: string } | ConfigDirective | ConfigDirective[] | ((ctx: EditorContext) => ConfigActionResult)`,
    `export type WorkspaceTab = 'code' | 'process' | 'ai'`,
    `export type QeTask = { name: string; command: string; cwd?: string; runCommand?: string; errorRegex?: string; autoJumpToError?: boolean; closePanelOnSuccess?: boolean; timeoutSeconds?: number; tab?: 'process' | 'shell' }`,
    `export type QeProjectProfile = { name: string; root?: string; files?: string[]; tasks?: QeTask[] }`,
    `export type WorkspaceConfig = { roots?: string[]; ignore?: string[]; allow?: string[] }`,
    `export type QeConfig = {`,
    `  preset?: 'web' | 'rust' | 'minimal'`,
    `  extras?: QeExtra[]`,
    `  theme?: Partial<Record<'bg' | 'fg' | 'grey' | 'red' | 'orange' | 'green' | 'yellow' | 'blue' | 'magenta' | 'cyan' | 'violet', string>>`,
    `  leader?: { [key: string]: ConfigAction | QeConfig['leader'] }`,
    `  hooks?: { ${CONFIG_API_HOOK_NAMES.map(name => `${name}?: ConfigAction`).join('; ')} }`,
    `  commands?: Record<string, ConfigAction>`,
    `  tasks?: QeTask[]`,
    `  projects?: QeProjectProfile[]`,
    `  workspace?: WorkspaceConfig`,
    `}`,
    `export function defineConfig<const T extends QeConfig>(config: T): T { return config }`,
  ].join('\n')
}

export function starterConfigTemplate(): string {
  return [
    `// ~/.config/qe/config.ts - qe programmable editor config`,
    `// This file is trusted local code. It can use command IDs, directives, or functions.`,
    `import { defineConfig } from './config-api.ts'`,
    ``,
    `export default defineConfig({`,
    `  preset: 'web',`,
    `  extras: ['typescript', 'git', 'ai', 'formatting'],`,
    `  tasks: [`,
    `    { name: 'typecheck', command: 'npm run typecheck', tab: 'process', autoJumpToError: true },`,
    `    { name: 'app tests', command: 'npm --prefix app run test', tab: 'process' },`,
    `    { name: 'editor-core tests', command: 'cargo test --manifest-path native/editor-core/Cargo.toml', tab: 'process' },`,
    `  ],`,
    `  workspace: {`,
    `    roots: ['.'],`,
    `    ignore: [],`,
    `    allow: [],`,
    `  },`,
    ``,
    `  commands: {`,
    `    // Override built-in commands here if needed.`,
    `  },`,
    ``,
    `  leader: {`,
    `    p: { t: 'tasks.pickAndRun' },`,
    `    x: { t: [`,
    `      { type: 'shell.run', command: 'npm test' },`,
    `      { type: 'panel.open', panel: 'shell' },`,
    `    ] },`,
    `    z: { r: (ctx) => ctx.shell.run('cargo test') },`,
    `  },`,
    ``,
    `  hooks: {`,
    `    // Hooks support commands/directives. Modal UI prompts are only available from leader/commands.`,
    `    onSave: async (ctx) => {`,
    `      if (ctx.filename?.endsWith('.ts')) await ctx.commands.run('code.format')`,
    `    },`,
    `    // onBufEnter: (ctx) => ctx.ui.notify(\`buf \${ctx.filename ?? 'scratch'}\`, 'info'),`,
    `    // onShellDone: (ctx) => {`,
    `    //   const run = ctx.lastShellRun`,
    `    //   if (run?.exitCode) ctx.ui.notify(\`failed: \${run.command}\`, 'error')`,
    `    // },`,
    `    // onChange fires only when content revision changes, after the initial snapshot, debounced by 250ms.`,
    `    // onChange: { type: 'ui.notify', message: 'buffer changed' },`,
    `  },`,
    `})`,
  ].join('\n')
}
